version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "33306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: v6SxhWHyZC7S
      MYSQL_DATABASE: linkme
    volumes:
      - ./data/mysql/data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    restart: always
    networks:
      - linkme_net

  redis:
    image: redis:6.2.5
    container_name: redis
    restart: always
    ports:
      - "36379:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis/data:/data:rw
    command:
      - "redis-server"
      - "--bind"
      - "0.0.0.0"
      - "--protected-mode"
      - "no"
      - "--requirepass"
      - "v6SxhWHyZC7S"
      - "--appendonly"
      - "yes"
    networks:
      - linkme_net

  kafka:
    image: bitnami/kafka:3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_KRAFT_CLUSTER_ID=LlMmNnOoPp
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
    volumes:
      - ./data/kafka/data:/bitnami/kafka/data:rw
    networks:
      - linkme_net

  filebeat:
    image: elastic/filebeat:8.12.2
    container_name: filebeat
    environment:
      TZ: Asia/Shanghai
    user: root
    restart: always
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - ./deploy/filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - linkme_net
    depends_on:
      - kafka

  logstash:
    image: logstash:8.12.2
    container_name: logstash
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./deploy/logstash/conf/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./deploy/logstash/pipeline:/usr/share/logstash/pipeline # 日志处理管道
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - linkme_net
    depends_on:
      - elasticsearch
      - kafka

  #####注意：如果访问Kibana需要访问令牌，请检查es许可证是否开启，如果没有开启，使用下述命令开启#####
  # curl -X POST "localhost:9200/_license/start_trial?acknowledge=true" -u elastic:changeme

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.12.2
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "TZ=Asia/Shanghai"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/es/data:/usr/share/elasticsearch/data
      - ./data/es/plugins:/usr/share/elasticsearch/plugins
    networks:
      - linkme_net

  kibana:
    container_name: kibana
    image: kibana:8.12.2
    restart: always
    environment:
      - "TZ=Asia/Shanghai"
      - "I18N_LOCALE=zh-CN"
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - "XPACK_SECURITY_ENABLED=false"
    ports:
      - "5601:5601"
    networks:
      - linkme_net
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./deploy/prometheus/server/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always
    user: root
    ports:
      - 9090:9090
    networks:
      - linkme_net

  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    hostname: grafana
    user: root
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
      GF_SECURITY_ADMIN_USER: admin          # 默认管理员用户名
      GF_SECURITY_ADMIN_PASSWORD: admin   # 默认管理员密码
    restart: always
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3001:3000"
    networks:
      - linkme_net

  asynqmon:
    image: hibiken/asynqmon:latest
    container_name: asynqmon
    ports:
      - 8980:8080
    command:
      - '--redis-addr=redis:6379'
      - '--redis-password=v6SxhWHyZC7S'
    restart: always
    networks:
      - linkme_net
    depends_on:
      - redis

networks:
  linkme_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
